version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: backend-postgres-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wintense
      POSTGRES_PASSWORD: wintense
      POSTGRES_DB: wintensecare
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: